### ISSUE TITLE
在Windows10下安装失败，Unhandled rejection TypeError？

### ISSUE THREAD

**Issue by himao** [zthxxx/hexo-theme-Wikitten#1]
一直报错，重装了几次。安装前使用hexo s测试是正常的。
```
$ hexo g
INFO  Start processing
INFO  Files loaded in 508 ms
Unhandled rejection TypeError: D:\Wiki\themes\Wikitten\layout\page.ejs:1
 >> 1| <%- partial('common/article', {post: page, index: false}) %>

D:\Wiki\themes\Wikitten\layout\common\article.ejs:76
    74|
    75| <% if (!index) { %>
 >> 76|     <%- partial('comment/index') %>
    77| <% } %>
    78|
    79| <% if (!index){ %>

D:\Wiki\themes\Wikitten\layout\comment\index.ejs:2
    1| <% if (post.comments) { %>
 >> 2|     <% if (theme.comment.disqus) { %>
    3|         <section id="comments"> <%- partial('comment/disqus') %> </section>
    4|     <% } else if (theme.comment.duoshuo) { %>
    5|         <section id="comments"> <%- partial('comment/duoshuo') %> </section>

Cannot read property 'disqus' of undefined
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:110)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:661)
    at D:\Wiki\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (D:\Wiki\node_modules\hexo\lib\theme\view.js:122:20)
    at View.renderSync (D:\Wiki\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (D:\Wiki\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper (D:\Wiki\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:32:3782)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:32:4323)
    at D:\Wiki\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (D:\Wiki\node_modules\hexo\lib\theme\view.js:122:20)
    at View.renderSync (D:\Wiki\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (D:\Wiki\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper (D:\Wiki\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:99)
    at D:\Wiki\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (D:\Wiki\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (D:\Wiki\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\Wiki\node_modules\hexo\lib\hexo\index.js:387:25
    at tryCatcher (D:\Wiki\node_modules\bluebird\js\release\util.js:16:23)
    at D:\Wiki\node_modules\bluebird\js\release\method.js:15:34
Unhandled rejection TypeError: D:\Wiki\themes\Wikitten\layout\post.ejs:1
 >> 1| <%- partial('common/article', {post: page, index: false}) %>

D:\Wiki\themes\Wikitten\layout\common\article.ejs:13
    11|                         <%- partial('post/tag') %>
    12|                         <%- partial('post/date', { class_name: 'article-date', date_format: null }) %>
 >> 13|                         <% if (theme.history_control.enable) {
    14|                             let repertory_address = `${theme.history_control.server_link}/${theme.history_control.user}/${theme.history_control.repertory}`;
    15|                             let file_path = `${theme.history_control.branch}/source/${post.source}`;%>
    16|                             <div class="article-meta-button">

Cannot read property 'enable' of undefined
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:1030)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:32:4323)
    at D:\Wiki\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (D:\Wiki\node_modules\hexo\lib\theme\view.js:122:20)
    at View.renderSync (D:\Wiki\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (D:\Wiki\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper (D:\Wiki\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:99)
    at D:\Wiki\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (D:\Wiki\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (D:\Wiki\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\Wiki\node_modules\hexo\lib\hexo\index.js:387:25
    at tryCatcher (D:\Wiki\node_modules\bluebird\js\release\util.js:16:23)
    at D:\Wiki\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\Wiki\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Unhandled rejection TypeError: D:\Wiki\themes\Wikitten\layout\index.ejs:1
 >> 1| <%
    2| var indexArticle;
    3| var index_file = theme.customize.default_index_file;
    4| if(index_file) {

Cannot read property 'default_index_file' of undefined
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:32:33)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:43:23)
    at D:\Wiki\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (D:\Wiki\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (D:\Wiki\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\Wiki\node_modules\hexo\lib\hexo\index.js:387:25
    at tryCatcher (D:\Wiki\node_modules\bluebird\js\release\util.js:16:23)
    at D:\Wiki\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\Wiki\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
Unhandled rejection TypeError: D:\Wiki\themes\Wikitten\layout\layout.ejs:1
 >> 1| <%- partial('common/head') %>
    2| <body>
    3|     <div id="container">
    4|         <%- partial('common/header') %>

D:\Wiki\themes\Wikitten\layout\common\head.ejs:40
    38|     <% } %>
    39|     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
 >> 40|     <%- open_graph({
    41|         image:          thumbnail(page),
    42|         fb_app_id:      theme.miscellaneous.open_graph.fb_app_id,
    43|         fb_admins:      theme.miscellaneous.open_graph.fb_admins,

Cannot read property 'open_graph' of undefined
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:60:44)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:64:1152)
    at D:\Wiki\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (D:\Wiki\node_modules\hexo\lib\theme\view.js:122:20)
    at View.renderSync (D:\Wiki\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (D:\Wiki\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper (D:\Wiki\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:924)
    at D:\Wiki\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (D:\Wiki\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (D:\Wiki\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\Wiki\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (D:\Wiki\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Wiki\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Wiki\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Wiki\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Wiki\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\Wiki\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\Wiki\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\Wiki\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:649:20)
Unhandled rejection TypeError: D:\Wiki\themes\Wikitten\layout\layout.ejs:1
 >> 1| <%- partial('common/head') %>
    2| <body>
    3|     <div id="container">
    4|         <%- partial('common/header') %>

D:\Wiki\themes\Wikitten\layout\common\head.ejs:40
    38|     <% } %>
    39|     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
 >> 40|     <%- open_graph({
    41|         image:          thumbnail(page),
    42|         fb_app_id:      theme.miscellaneous.open_graph.fb_app_id,
    43|         fb_admins:      theme.miscellaneous.open_graph.fb_admins,

Cannot read property 'open_graph' of undefined
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:60:44)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:64:1152)
    at D:\Wiki\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (D:\Wiki\node_modules\hexo\lib\theme\view.js:122:20)
    at View.renderSync (D:\Wiki\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (D:\Wiki\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper (D:\Wiki\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:924)
    at D:\Wiki\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (D:\Wiki\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (D:\Wiki\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\Wiki\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (D:\Wiki\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Wiki\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Wiki\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Wiki\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Wiki\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\Wiki\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\Wiki\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\Wiki\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:649:20)
Unhandled rejection TypeError: D:\Wiki\themes\Wikitten\layout\layout.ejs:1
 >> 1| <%- partial('common/head') %>
    2| <body>
    3|     <div id="container">
    4|         <%- partial('common/header') %>

D:\Wiki\themes\Wikitten\layout\common\head.ejs:40
    38|     <% } %>
    39|     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
 >> 40|     <%- open_graph({
    41|         image:          thumbnail(page),
    42|         fb_app_id:      theme.miscellaneous.open_graph.fb_app_id,
    43|         fb_admins:      theme.miscellaneous.open_graph.fb_admins,

Cannot read property 'open_graph' of undefined
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:60:44)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:64:1152)
    at D:\Wiki\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (D:\Wiki\node_modules\hexo\lib\theme\view.js:122:20)
    at View.renderSync (D:\Wiki\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (D:\Wiki\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper (D:\Wiki\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:924)
    at D:\Wiki\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (D:\Wiki\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (D:\Wiki\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\Wiki\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (D:\Wiki\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Wiki\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Wiki\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Wiki\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Wiki\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\Wiki\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\Wiki\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\Wiki\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:649:20)
Unhandled rejection TypeError: D:\Wiki\themes\Wikitten\layout\layout.ejs:1
 >> 1| <%- partial('common/head') %>
    2| <body>
    3|     <div id="container">
    4|         <%- partial('common/header') %>

D:\Wiki\themes\Wikitten\layout\common\head.ejs:40
    38|     <% } %>
    39|     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
 >> 40|     <%- open_graph({
    41|         image:          thumbnail(page),
    42|         fb_app_id:      theme.miscellaneous.open_graph.fb_app_id,
    43|         fb_admins:      theme.miscellaneous.open_graph.fb_admins,

Cannot read property 'open_graph' of undefined
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:60:44)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:64:1152)
    at D:\Wiki\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (D:\Wiki\node_modules\hexo\lib\theme\view.js:122:20)
    at View.renderSync (D:\Wiki\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (D:\Wiki\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper (D:\Wiki\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:924)
    at D:\Wiki\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (D:\Wiki\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (D:\Wiki\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\Wiki\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (D:\Wiki\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Wiki\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Wiki\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Wiki\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Wiki\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\Wiki\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\Wiki\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\Wiki\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:649:20)
Unhandled rejection TypeError: D:\Wiki\themes\Wikitten\layout\layout.ejs:1
 >> 1| <%- partial('common/head') %>
    2| <body>
    3|     <div id="container">
    4|         <%- partial('common/header') %>

D:\Wiki\themes\Wikitten\layout\common\head.ejs:40
    38|     <% } %>
    39|     <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
 >> 40|     <%- open_graph({
    41|         image:          thumbnail(page),
    42|         fb_app_id:      theme.miscellaneous.open_graph.fb_app_id,
    43|         fb_admins:      theme.miscellaneous.open_graph.fb_admins,

Cannot read property 'open_graph' of undefined
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:60:44)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:64:1152)
    at D:\Wiki\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (D:\Wiki\node_modules\hexo\lib\theme\view.js:122:20)
    at View.renderSync (D:\Wiki\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (D:\Wiki\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper (D:\Wiki\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:35)
    at eval (eval at <anonymous> (D:\Wiki\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:924)
    at D:\Wiki\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (D:\Wiki\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (D:\Wiki\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\Wiki\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (D:\Wiki\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Wiki\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Wiki\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Wiki\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Wiki\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\Wiki\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\Wiki\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\Wiki\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:649:20)
ERROR Asset render failed: css/style.css
CoercionError: D:/Wiki/themes/Wikitten/source/css/_variables.styl:30:54
   26| // Header
   27| header-height = 48px
   28| header-sub-height = 36px
   29| logo-url = hexo-config("customize.logo.url")
   30| logo-width = 0px + hexo-config("customize.logo.width")
------------------------------------------------------------^
   31| logo-height = 0px + hexo-config("customize.logo.height")
   32|
   33| // Sidebar

cannot coerce '' to unit

    at Unit.coerce (D:\Wiki\node_modules\stylus\lib\nodes\node.js:248:11)
    at Unit.coerce (D:\Wiki\node_modules\stylus\lib\nodes\unit.js:209:43)
    at Unit.operate (D:\Wiki\node_modules\stylus\lib\nodes\unit.js:132:20)
    at Evaluator.visitBinOp (D:\Wiki\node_modules\stylus\lib\visitor\evaluator.js:567:28)
    at Evaluator.Visitor.visit (D:\Wiki\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\Wiki\node_modules\stylus\lib\visitor\evaluator.js:156:18)
    at Evaluator.visitExpression (D:\Wiki\node_modules\stylus\lib\visitor\evaluator.js:630:26)
    at Evaluator.Visitor.visit (D:\Wiki\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\Wiki\node_modules\stylus\lib\visitor\evaluator.js:156:18)
    at Evaluator.visitIdent (D:\Wiki\node_modules\stylus\lib\visitor\evaluator.js:537:22)
    at Evaluator.Visitor.visit (D:\Wiki\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\Wiki\node_modules\stylus\lib\visitor\evaluator.js:156:18)
    at Evaluator.visitBlock (D:\Wiki\node_modules\stylus\lib\visitor\evaluator.js:706:39)
    at Evaluator.Visitor.visit (D:\Wiki\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\Wiki\node_modules\stylus\lib\visitor\evaluator.js:156:18)
    at Evaluator.importFile (D:\Wiki\node_modules\stylus\lib\visitor\evaluator.js:95:18)
    at Evaluator.visitImport (D:\Wiki\node_modules\stylus\lib\visitor\evaluator.js:906:27)
    at Evaluator.Visitor.visit (D:\Wiki\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\Wiki\node_modules\stylus\lib\visitor\evaluator.js:156:18)
    at Evaluator.visitRoot (D:\Wiki\node_modules\stylus\lib\visitor\evaluator.js:693:27)
    at Evaluator.Visitor.visit (D:\Wiki\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\Wiki\node_modules\stylus\lib\visitor\evaluator.js:156:18)
INFO  Generated: robots.txt
INFO  Generated: css/images/thumb-default-small.png
INFO  Generated: libs/fonts/glyphicons-halflings-regular.eot
INFO  Generated: js/insight.js
INFO  Generated: libs/open-sans/styles.css
INFO  Generated: libs/justified-gallery/justifiedGallery.min.css
INFO  Generated: libs/source-code-pro/styles.css
INFO  Generated: css/style.css
INFO  Generated: css/images/favicon.ico
INFO  Generated: js/main.js
INFO  Generated: libs/fonts/glyphicons-halflings-regular.ttf
INFO  Generated: libs/justified-gallery/jquery.justifiedGallery.min.js
INFO  Generated: libs/fonts/glyphicons-halflings-regular.woff
INFO  Generated: libs/fonts/glyphicons-halflings-regular.woff2
INFO  Generated: libs/font-awesome/fonts/FontAwesome.otf
INFO  Generated: images/SitePreview.png
INFO  Generated: css/images/logo.png
INFO  Generated: libs/fonts/glyphicons-halflings-regular.svg
INFO  Generated: libs/font-awesome/fonts/fontawesome-webfont.woff
INFO  Generated: libs/font-awesome/fonts/fontawesome-webfont.woff2
INFO  Generated: libs/font-awesome/fonts/fontawesome-webfont.eot
INFO  Generated: libs/jquery/2.1.3/jquery.min.js
INFO  Generated: libs/lightgallery/js/lg-autoplay.js
INFO  Generated: libs/font-awesome/css/font-awesome.min.css
INFO  Generated: libs/lightgallery/css/lg-fb-comment-box.css
INFO  Generated: libs/lightgallery/fonts/lg.eot
INFO  Generated: libs/lightgallery/img/loading.gif
INFO  Generated: libs/open-sans/fonts/59ZRklaO5bWGqF5A9baEERJtnKITppOI_IvcXXDNrsc.woff2
INFO  Generated: libs/source-code-pro/fonts/mrl8jkM18OlOQN8JLgasD9V_2ngZ8dMf8fLgjYEouxg.woff2
INFO  Generated: libs/lightgallery/css/lg-fb-comment-box.min.css
INFO  Generated: libs/lightgallery/js/lg-autoplay.min.js
INFO  Generated: libs/font-awesome/fonts/fontawesome-webfont.svg
INFO  Generated: libs/lightgallery/js/lg-fullscreen.min.js
INFO  Generated: libs/lightgallery/js/lg-fullscreen.js
INFO  Generated: libs/lightgallery/js/lg-hash.js
INFO  Generated: libs/lightgallery/js/lg-pager.min.js
INFO  Generated: libs/lightgallery/js/lg-hash.min.js
INFO  Generated: libs/lightgallery/js/lg-thumbnail.min.js
INFO  Generated: libs/lightgallery/js/lg-video.js
INFO  Generated: libs/lightgallery/js/lg-video.min.js
INFO  Generated: libs/lightgallery/js/lg-share.js
INFO  Generated: libs/lightgallery/js/lg-share.min.js
INFO  Generated: libs/lightgallery/js/lg-pager.js
INFO  Generated: libs/lightgallery/js/lg-zoom.min.js
INFO  Generated: libs/lightgallery/css/lg-transitions.css
INFO  Generated: libs/font-awesome/css/font-awesome.css
INFO  Generated: libs/lightgallery/css/lg-transitions.min.css
INFO  Generated: libs/lightgallery/js/lg-thumbnail.js
INFO  Generated: libs/lightgallery/css/lightgallery.min.css
INFO  Generated: libs/lightgallery/js/lightgallery.js
INFO  Generated: libs/lightgallery/js/lg-zoom.js
INFO  Generated: libs/font-awesome/fonts/fontawesome-webfont.ttf
INFO  Generated: libs/lightgallery/js/lightgallery.min.js
INFO  Generated: libs/lightgallery/css/lightgallery.css
INFO  Generated: libs/lightgallery/css/lg-transitions.css.map
INFO  Generated: libs/lightgallery/fonts/lg.svg
INFO  Generated: libs/lightgallery/css/lightgallery.css.map
INFO  Generated: libs/lightgallery/fonts/lg.ttf
INFO  Generated: libs/lightgallery/css/lg-fb-comment-box.css.map
INFO  Generated: libs/lightgallery/img/video-play.png
INFO  Generated: libs/lightgallery/fonts/lg.woff
INFO  Generated: libs/lightgallery/img/vimeo-play.png
INFO  Generated: libs/open-sans/fonts/K88pR3goAWT7BTt32Z01mxJtnKITppOI_IvcXXDNrsc.woff2
INFO  Generated: libs/lightgallery/img/youtube-play.png
INFO  Generated: libs/open-sans/fonts/LWCjsQkB6EMdfHrEVqA1KRJtnKITppOI_IvcXXDNrsc.woff2
INFO  Generated: libs/open-sans/fonts/MTP_ySUJH_bn48VBG8sNShWV49_lSm1NYrwo-zkhivY.woff2
INFO  Generated: libs/open-sans/fonts/MTP_ySUJH_bn48VBG8sNSj0LW-43aMEzIO6XUTLjad8.woff2
INFO  Generated: libs/open-sans/fonts/MTP_ySUJH_bn48VBG8sNSqaRobkAwv3vxw3jMhVENGA.woff2
INFO  Generated: libs/open-sans/fonts/MTP_ySUJH_bn48VBG8sNSpX5f-9o1vgP2EXwfjgl7AY.woff2
INFO  Generated: libs/open-sans/fonts/MTP_ySUJH_bn48VBG8sNSq-j2U0lmluP9RWlSytm3ho.woff2
INFO  Generated: libs/open-sans/fonts/MTP_ySUJH_bn48VBG8sNSugdm0LZdjqr5-oayXSOefg.woff2
INFO  Generated: libs/open-sans/fonts/MTP_ySUJH_bn48VBG8sNSv8zf_FOSsgRmwsS7Aa9k2w.woff2
INFO  Generated: libs/open-sans/fonts/RjgO7rYTmqiVp7vzi-Q5URJtnKITppOI_IvcXXDNrsc.woff2
INFO  Generated: libs/open-sans/fonts/cJZKeOuBrn4kERxqtaUH3VtXRa8TVwTICgirnJhmVJw.woff2
INFO  Generated: libs/open-sans/fonts/u-WUoqrET9fUeobQW7jkRRJtnKITppOI_IvcXXDNrsc.woff2
INFO  Generated: libs/open-sans/fonts/xjAJXh38I15wypJXxuGMBiYE0-AqJ3nfInTTiDXDjU4.woff2
INFO  Generated: libs/open-sans/fonts/xjAJXh38I15wypJXxuGMBjTOQ_MqJVwkKsUn0wKzc2I.woff2
INFO  Generated: libs/open-sans/fonts/xjAJXh38I15wypJXxuGMBjUj_cnvWIuuBMVgbX098Mw.woff2
INFO  Generated: libs/open-sans/fonts/xjAJXh38I15wypJXxuGMBkbcKLIaa1LC45dFaAfauRA.woff2
INFO  Generated: libs/open-sans/fonts/xjAJXh38I15wypJXxuGMBmo_sUJ8uO4YLWRInS22T3Y.woff2
INFO  Generated: libs/source-code-pro/fonts/mrl8jkM18OlOQN8JLgasDy2Q8seG17bfDXYR_jUsrzg.woff2
INFO  Generated: libs/open-sans/fonts/xjAJXh38I15wypJXxuGMBo4P5ICox8Kq3LLUNMylGO4.woff2
INFO  Generated: libs/open-sans/fonts/xjAJXh38I15wypJXxuGMBr6up8jxqWt8HVA3mDhkV_0.woff2
INFO  Generated: libs/open-sans/fonts/xozscpT2726on7jbcb_pAhJtnKITppOI_IvcXXDNrsc.woff2
INFO  Generated: libs/jquery/plugins/cookie/1.4.1/jquery.cookie.js
$ 
```

**Comment by wadefelix** [comment]
我这个周末也想弄个这docker image，配置还是挺复杂，没搞定

**Comment by zthxxx** [comment]
根据报错来看，是主题配置中的这几项配置缺失；但是看你同时出现这么多缺失项，有理由怀疑你是不是根本没有主题 `_config.yml` 文件。
请再次确认是否正确放置主题配置文件，并确认是否按 README 中的相关说明进行配置：
https://github.com/zthxxx/hexo-theme-Wikitten#configuration

**Comment by wadefelix** [comment]
@zthxxx 麻烦最好把包括hexo默认的那些 site name配置项的内容都包含到这个配置说明里。

**Comment by zthxxx** [comment]
@wadefelix 不是很清楚你的意思，
我在 README 中明确写了需要安装的 node 的包有哪些，在配置项说明中也**明确**写了需要的 **站点配置** 和 **主题配置**，同时也给出了完全可以**直接使用**的主题配置参考文件 [`_config.yml.example`](https://github.com/zthxxx/hexo-theme-Wikitten/blob/master/_config.yml.example) 。
配置上你可以直接尝试像 README 里面那样直接复制参考配置文件：
```bash
$ cd your-hexo-directory
$ cp -f themes/Wikitten/_config.yml.example themes/Wikitten/_config.yml
```

至于你之前说的 Docker 部署，我的 Wiki 站点使用的 [Travis-CI ](https://travis-ci.org/)做的自动部署，而 Travis-CI 在构建时就是拉取的 Docker Image，所以你如果想通过 Docker 部署，可以直接参考我站点的 `.travis.yml` 文件：
https://github.com/zthxxx/Wiki-site/blob/writing/.travis.yml

**Comment by himao** [comment]
@zthxxx 额 的确没有主题配置文件的问题。新手上路，以前的主题都是下来直接用了。抱歉抱歉，问题太低级。再调整调整，开始自己的wiki了。感谢创造分享。

**Comment by zthxxx** [comment]
@himao 没关系，有问题就提出来也是好的，欢迎使用

**Comment by Supertraveler-Lee** [comment]
你好 挺喜欢你这个主题：） 我这几天尝试使用后有遇到一些麻烦
具体如下:
  hexo g后出现错误 warn partial common/article does not exist (in post.ejs)  然后我部署成功后可以看到主题皮肤 在归档中也可以看到文章列表 但是点击后看不见文章

**Comment by zthxxx** [comment]
@Supertraveler-Lee  检查下 `article.ejs` 这个文件是否存在  `Wikitten/layout/common/article.ejs`，不存在的话请重新安装主题。

**Comment by Supertraveler-Lee** [comment]
@zthxxx 检查过是有的 所以觉得奇怪
