### ISSUE TITLE
一些插件问题

### ISSUE THREAD

**Issue by tommars00** [zthxxx/hexo-theme-Wikitten#16]
我特别喜欢你的wiki-theme，很想用，但是出了些插件问题，想问下该如何解决。主要是“hexo-directory-category"和"hexo-generator-json-content"，不知道是不是我的配置文件除了问题没。

下面是我的出错报告：
我的blog的安装目录是“/root/HEXO/blog”。

ERROR Plugin load failed: hexo-directory-category
TypeError: rule must be a function, a string or a regular expression.
    at new Pattern (/root/HEXO/blog/node_modules/hexo/node_modules/hexo-util/lib/pattern.js:17:11)
    at Processor.register (/root/HEXO/blog/node_modules/hexo/lib/extend/processor.js:31:14)
    at /root/HEXO/blog/node_modules/hexo-directory-category/index.js:14:23
    at /root/HEXO/blog/node_modules/hexo/lib/hexo/index.js:232:12
    at tryCatcher (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:638:18)
    at /root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /root/HEXO/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
ERROR Plugin load failed: hexo-generator-json-content
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at Object.exports.runInThisContext (vm.js:53:16)
    at /root/HEXO/blog/node_modules/hexo/lib/hexo/index.js:230:17
    at tryCatcher (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:638:18)
    at /root/HEXO/blog/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /root/HEXO/blog/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

如蒙赐教，不胜感激。

**Comment by zthxxx** [comment]
这个报错看起来不是很清楚，这个问题是你安装插件报错，还是运行 `hexo s` 时报错的？

**Comment by zthxxx** [comment]
你可以先尝试手动安装这两个插件，

```bash
$ npm install --save hexo-directory-category
$ npm install --save hexo-generator-json-content
```

然后使用本项目给出的推荐配置：
https://github.com/zthxxx/hexo-theme-Wikitten#configuration
```yaml
### JsonContent
jsonContent:
  meta: false
  pages:
    title: true
    date: true
    path: true
    text: true
  posts:
    title: true
    date: true
    path: true
    text: true
    tags: true
    categories: true
  ignore:
    - 404.html
```

**Comment by tommars00** [comment]
谢谢您的耐心回复。是我自己对hexo不够熟悉。
问题已解决。我仔细查看了下安装hexo-generator-json-content时他的信息，提示我安装的nodejs版本过低，要求是6.x以上，我的才4.x。
国庆节了还打扰到您，真的非常抱歉。
祝您国庆快乐。

**Comment by zthxxx** [comment]
感谢你的使用，不用太过客气
