### ISSUE TITLE
ERROR Plugin load failed: hexo-directory-category

### ISSUE THREAD

**Issue by hmgqzx** [zthxxx/hexo-theme-Wikitten#20]
报错信息：
>ERROR Plugin load failed: hexo-directory-category
TypeError: rule must be a function, a string or a regular expression.
    at new Pattern (/Users/me/wiki-site/node_modules/hexo/node_modules/hexo-util/lib/pattern.js:17:11)
    at Processor.register (/Users/me/wiki-site/node_modules/hexo/lib/extend/processor.js:31:14)
    at /Users/me/wiki-site/node_modules/hexo-directory-category/index.js:14:23
    at /Users/me/wiki-site/node_modules/hexo/lib/hexo/index.js:232:12
    at tryCatcher (/Users/me/wiki-site/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/me/wiki-site/node_modules/hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/me/wiki-site/node_modules/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/me/wiki-site/node_modules/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/me/wiki-site/node_modules/hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/me/wiki-site/node_modules/hexo/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/me/wiki-site/node_modules/hexo/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/me/wiki-site/node_modules/hexo/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/me/wiki-site/node_modules/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/me/wiki-site/node_modules/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/me/wiki-site/node_modules/hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/me/wiki-site/node_modules/hexo/node_modules/bluebird/js/release/promise.js:638:18)
    at /Users/me/wiki-site/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/me/wiki-site/node_modules/hexo/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:532:3)

尝试过用以下命令重装 hexo 和 该插件：
```
npm uninstall -g hexo-cli
npm install -g hexo-cli

rm -rvf node_modules
npm install

npm install --save hexo-directory-category
```
安装过程中没有报错信息，但运行
```
hexo c
hexo s -g --debug
```
就会报这个错误，且侧边分类栏无法显示

**Comment by zthxxx** [comment]
确认这个报错是由于插件 `hexo-directory-category` 的 1.0.3 版不支持新版 Hexo 导致的，

对应依赖升级就好了，顺便也升级下主题更好

`npm i -S hexo-directory-category`

还有版本问题的话，再尝试下清空 `node_modules` 重装试试

**Comment by OHLIA** [comment]
hexo 3.9.0,
hexo-directory-category 1.0.7,

同样回报这个问题。

清空 node_modules，
运行 npm install 重装,问题依旧。

```
$ hexo -g --debug                                                                03:08:29.916 DEBUG Writing database to D:\Documents\GitHub\hexo/db.json          03:08:29.954 DEBUG Hexo version: 3.9.0                                           03:08:29.954 DEBUG Working directory: D:\Documents\GitHub\hexo\                  03:08:30.213 DEBUG Config loaded: D:\Documents\GitHub\hexo\_config.yml           03:08:30.532 DEBUG Plugin loaded: hexo-deployer-git                              03:08:30.685 DEBUG Plugin loaded: hexo-autonofollow                              03:08:30.733 DEBUG Plugin loaded: hexo-generator-archive                         03:08:30.741 DEBUG Plugin loaded: hexo-generator-feed                            03:08:30.747 DEBUG Plugin loaded: hexo-generator-category                        03:08:30.748 ERROR Plugin load failed: hexo-directory-category                   TypeError: rule must be a function, a string or a regular expression.                at new Pattern (D:\Documents\GitHub\hexo\node_modules\hexo\node_modules\hexo -util\lib\pattern.js:17:11)                                                          at Processor.register (D:\Documents\GitHub\hexo\node_modules\hexo\lib\extend \processor.js:31:14)                                                                 at D:\Documents\GitHub\hexo\node_modules\hexo-directory-category\index.js:14 :23                                                                                  at fs.readFile.then.script (D:\Documents\GitHub\hexo\node_modules\hexo\lib\h exo\index.js:232:12)                                                                 at tryCatcher (D:\Documents\GitHub\hexo\node_modules\hexo\node_modules\blueb ird\js\release\util.js:16:23)                                                        at Promise._settlePromiseFromHandler (D:\Documents\GitHub\hexo\node_modules\ hexo\node_modules\bluebird\js\release\promise.js:517:31)                             at Promise._settlePromise (D:\Documents\GitHub\hexo\node_modules\hexo\node_m odules\bluebird\js\release\promise.js:574:18)                                        at Promise._settlePromise0 (D:\Documents\GitHub\hexo\node_modules\hexo\node_ modules\bluebird\js\release\promise.js:619:10)                                       at Promise._settlePromises (D:\Documents\GitHub\hexo\node_modules\hexo\node_ modules\bluebird\js\release\promise.js:699:18)                                       at Promise._fulfill (D:\Documents\GitHub\hexo\node_modules\hexo\node_modules \bluebird\js\release\promise.js:643:18)                                              at Promise._resolveCallback (D:\Documents\GitHub\hexo\node_modules\hexo\node _modules\bluebird\js\release\promise.js:437:57)                                      at Promise._settlePromiseFromHandler (D:\Documents\GitHub\hexo\node_modules\ hexo\node_modules\bluebird\js\release\promise.js:529:17)                             at Promise._settlePromise (D:\Documents\GitHub\hexo\node_modules\hexo\node_m odules\bluebird\js\release\promise.js:574:18)                                        at Promise._settlePromise0 (D:\Documents\GitHub\hexo\node_modules\hexo\node_ modules\bluebird\js\release\promise.js:619:10)                                       at Promise._settlePromises (D:\Documents\GitHub\hexo\node_modules\hexo\node_ modules\bluebird\js\release\promise.js:699:18)                                       at Promise._fulfill (D:\Documents\GitHub\hexo\node_modules\hexo\node_modules \bluebird\js\release\promise.js:643:18)                                              at D:\Documents\GitHub\hexo\node_modules\hexo\node_modules\bluebird\js\relea se\nodeback.js:42:21                                                                 at D:\Documents\GitHub\hexo\node_modules\graceful-fs\graceful-fs.js:78:16        at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_conte xt.js:53:3)                                                                      03:08:30.753 DEBUG Plugin loaded: hexo-generator-index                           03:08:30.996 DEBUG Plugin loaded: hexo-generator-json-content                    03:08:31.001 DEBUG Plugin loaded: hexo-generator-tag                             03:08:31.007 DEBUG Plugin loaded: hexo-generator-sitemap                         03:08:31.015 DEBUG Plugin loaded: hexo-renderer-ejs                              03:08:31.130 DEBUG Plugin loaded: hexo-renderer-marked                           03:08:31.132 DEBUG Plugin loaded: hexo-renderer-stylus                           03:08:31.310 DEBUG Plugin loaded: hexo-server                                    03:08:31.314 DEBUG Script loaded: themes\wikitten\scripts\meta.js                03:08:31.314 DEBUG Script loaded: themes\wikitten\scripts\thumbnail.js
```

**Comment by zthxxx** [comment]
@OHLIA  请把 `packages.json` 中 hexo 版本将为 3.7.0 和 3.6.0 再分别重装了发一下日志

**Comment by OHLIA** [comment]
> @OHLIA 请把 `packages.json` 中 hexo 版本将为 3.7.0 和 3.6.0 再分别重装了发一下日志

我换一台电脑同样的 HEXO 3.9.0 版本没出问题，
前面那台电脑不知道是环境配置哪里出问题了。

**Comment by zthxxx** [comment]
@OHLIA  光想也没用，你要我帮忙，至少把日志发一下我才有信息

<details>日志放在 details 这个标签中</details>
