### ISSUE TITLE
cannot coerce '' to unit

### ISSUE THREAD

**Issue by scriptwang** [zthxxx/hexo-theme-Wikitten#42]
$ hexo s
(node:14100) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
ERROR Asset render failed: css/style.css
CoercionError: D:/hexo/themes/Wikitten/source/css/_variables.styl:30:54
   26| // Header
   27| header-height = 48px
   28| header-sub-height = 36px
   29| logo-url = hexo-config("customize.logo.url")
   30| logo-width = 0px + hexo-config("customize.logo.width")
------------------------------------------------------------^
   31| logo-height = 0px + hexo-config("customize.logo.height")
   32|
   33| // Sidebar

cannot coerce '' to unit

    at Unit.coerce (D:\hexo\node_modules\stylus\lib\nodes\node.js:248:11)
    at Unit.coerce (D:\hexo\node_modules\stylus\lib\nodes\unit.js:209:43)
    at Unit.operate (D:\hexo\node_modules\stylus\lib\nodes\unit.js:132:20)
    at Evaluator.visitBinOp (D:\hexo\node_modules\stylus\lib\visitor\evaluator.js:581:28)
    at Evaluator.Visitor.visit (D:\hexo\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\hexo\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitExpression (D:\hexo\node_modules\stylus\lib\visitor\evaluator.js:644:26)
    at Evaluator.Visitor.visit (D:\hexo\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (D:\hexo\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitIdent (D:\hexo\node_modules\stylus\lib\visitor\evaluator.js:551:22)

**Comment by zthxxx** [comment]
看报错就是少了一个参数吧

**Comment by scriptwang** [comment]
没读到logo的数据，手动写死了
