### ISSUE TITLE
加载这个主题包出错

### ISSUE THREAD

**Issue by LarryBug** [zthxxx/hexo-theme-Wikitten#84]
INFO  Validating config
INFO  Start processing
INFO  Hexo is running at http://localhost:4000 . Press Ctrl+C to stop.
Unhandled rejection TypeError: /Users/larry/blog/themes/Wikitten/layout/index.ejs:1
 >> 1| <% 
    2| var indexArticle;
    3| var index_file = theme.customize.default_index_file;
    4| if(index_file) {

Cannot read properties of undefined (reading 'default_index_file')
    at eval ("/Users/larry/blog/themes/Wikitten/layout/index.ejs":12:34)
    at index (/Users/larry/blog/node_modules/ejs/lib/ejs.js:692:17)
    at _View._compiled (/Users/larry/blog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/Users/larry/blog/node_modules/hexo/lib/theme/view.js:39:17)
    at /Users/larry/blog/node_modules/hexo/lib/hexo/index.js:64:21
    at tryCatcher (/Users/larry/blog/node_modules/bluebird/js/release/util.js:16:23)
    at /Users/larry/blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/Users/larry/blog/node_modules/hexo/lib/hexo/router.js:47:5)
    at RouteStream.Readable.read (node:internal/streams/readable:487:10)
    at resume_ (node:internal/streams/readable:988:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by tangchn** [comment]
你检查一下 themes/Wikitten/_config.yml 文件是否存在，作者好像默认ignore掉了 _config.yml文件。
