### ISSUE TITLE
Hexo 7.0.0 error 无法正常使用

### ISSUE THREAD

**Issue by rchangl** [zthxxx/hexo-theme-Wikitten#99]
Hexo 7.0.0 用不了了， hexo g hexo s 都会有error，页面也无法像旧版 Hexo 一样正常访问

**Comment by rchangl** [comment]
Logo错误那里改一下好像就好了
css/style.css
```
CoercionError: C:/aacore/rchangl/themes/Wikitten/source/css/_variables.styl:30:54
   26| // Header
   27| header-height = 48px
   28| header-sub-height = 36px
   29| logo-url = hexo-config("customize.logo.url")
   30| logo-width = 0px + hexo-config("customize.logo.width")
------------------------------------------------------------^
   31| logo-height = 0px + hexo-config("customize.logo.height")
   32|
   33| // Sidebar

cannot coerce '' to unit

    at Unit.coerce (C:\aacore\rchangl\node_modules\stylus\lib\nodes\node.js:250:11)
    at Unit.coerce (C:\aacore\rchangl\node_modules\stylus\lib\nodes\unit.js:209:43)
    at Unit.operate (C:\aacore\rchangl\node_modules\stylus\lib\nodes\unit.js:132:20)
    at Evaluator.visitBinOp (C:\aacore\rchangl\node_modules\stylus\lib\visitor\evaluator.js:581:28)
    at Visitor.visit (C:\aacore\rchangl\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\aacore\rchangl\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitExpression (C:\aacore\rchangl\node_modules\stylus\lib\visitor\evaluator.js:644:26)
    at Visitor.visit (C:\aacore\rchangl\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\aacore\rchangl\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitIdent (C:\aacore\rchangl\node_modules\stylus\lib\visitor\evaluator.js:551:22)
    at Visitor.visit (C:\aacore\rchangl\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\aacore\rchangl\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitBlock (C:\aacore\rchangl\node_modules\stylus\lib\visitor\evaluator.js:720:39)
    at Visitor.visit (C:\aacore\rchangl\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\aacore\rchangl\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.importFile (C:\aacore\rchangl\node_modules\stylus\lib\visitor\evaluator.js:99:18)
    at Evaluator.visitImport (C:\aacore\rchangl\node_modules\stylus\lib\visitor\evaluator.js:920:27)
    at Visitor.visit (C:\aacore\rchangl\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\aacore\rchangl\node_modules\stylus\lib\visitor\evaluator.js:160:18)
    at Evaluator.visitRoot (C:\aacore\rchangl\node_modules\stylus\lib\visitor\evaluator.js:707:27)
    at Visitor.visit (C:\aacore\rchangl\node_modules\stylus\lib\visitor\index.js:28:40)
    at Evaluator.visit (C:\aacore\rchangl\node_modules\stylus\lib\visitor\evaluator.js:160:18)
```

**Comment by rchangl** [comment]
https://github.com/rchangl/hexo-theme-Wikitten/tree/master
删除了一些用不到，可能会引发错误的部分（卜算子、历史版本）
